# Generated by Django 4.2.19 on 2025-02-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='language',
            field=models.CharField(default='en', max_length=7),
            preserve_default=False,
        ),
    ]
